# Paper button that launches a detangle child profile

package(default_visibility = ["//visibility:public"])

load("//defs:defs.bzl", "web_lib")

web_lib(
    name = "detangle-style",
    srcs = [
        "detangle-style.html",
    ],
    path = "/detangle-style",
    deps = [
        "@org_polymer",
    ],
)
