# Body of a page that handles events where navigation was intercepted.

package(default_visibility = ["//visibility:public"])

load("//defs:defs.bzl", "detangle_component")

detangle_component(
    name = "detangle-intercepted-page",
    component_deps = [
        "//chrome_ext/components/detangle-event-card",
        "@org_polymer",
        "@org_polymer_paper_material",
        "@org_polymer_paper_toolbar",
    ],
)
